rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    queue:
      proposta-pendente: proposta-pendente.ms-analise-credito
    exchanges:
      proposta-concluida: proposta-concluida.ex