spring:
    datasource:
        url: ${POSTGRES_HOST:jdbc:postgresql://localhost:5432/proposta_db}
        username: ${POSTGRES_USERNAME:postgres}
        password: ${POSTGRES_PASSWORD:postgres}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
        queue:
          proposta-concluida: proposta-concluida.ms-proposta
          proposta-pendente-dlq: proposta-pendente.dlq
        exchanges:
            proposta-pendente: proposta-pendente.ex
            proposta-pendente-dlx: proposta-pendente-dlx.ex
            proposta-concluida: proposta-concluida.ex
        listener:
            simple:
                retry:
                    enable: true
                    max-attempts: 3