version: '3.5'
services:
  proposta-app:
    image: proposta-ms
    environment:
      spring.profiles.active: prod
    depends_on:
      rabbit-mq:
        condition: service_healthy
    ports:
      - "8080:8080"
    command: [ "sh", "-c", "sleep 10 && java -Duser.language=pt -Duser.country=BR -jar proposta-backend.jar" ]
  rabbit-mq:
    image: rabbitmq:3-management
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      timeout: 5s
      interval: 5s
      retries: 3
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: proposta_db