rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    queue:
      proposta-pendente: proposta-pendente.ms-notificacao
aws:
    accessKey: ${AWS_ACCESS_KEY}
    secretKey: ${AWS_SECRET_KEY}